name: test

on:
  push:
    tags:
      - 'test_*'

jobs:
  test:
    permissions:
      contents: write
    runs-on:
     - ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Commit report
        run: |
          git describe --tags > tag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git tag -f ${{ github.ref_name }}
          git push --tags --force
