name: test

on:
  push:
    tags:
      - 'test_*'

jobs:
  test:
    runs-on:
     - ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Test
        run: git describe --tags
      - name: Commit report
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
