name: test

on:
  push:
    tags:
      - 'test_*'

jobs:
  test:
    runs-on:
     - ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Test
        run: git describe --tags
